peliculas(1,accion,"The Eight Hundred", "En 1937, 300 soldados chinos luchan bajo un asedio dentro de un taller en el medio de un campo de batalla en Shanghái, completamente rodeados por el ejército japonés.",
          	"Zhi-zhong Huang, Zhang Junyi, Hao Ou", "2hr 28m", "Chino/Ingles/Español", 2020, "https://www.youtube.com/watch?v=kbikn8Q148c", "250").
peliculas(2,accion,"Crawl","Haley, una nadadora competitiva, se topa de frente con un huracán de categoría 5 que arrasa con su ciudad en Florida, para asegurarse de que su padre está bien. Una vez allí, descubre que la ciudad ha sido invadida por caimanes.",
            "Kaya Scodelario, Barry Pepper","1hr 27m", "Ingles/Español", 2019, "https://www.youtube.com/watch?v=H6MLJG0RdDE0", "200").
peliculas(3,accion,"The Informer","Un ex-convicto trabajando de encubierto logra, de manera intencional, que lo encarcelen nuevamente, para infiltrarse dentro de una mafia que existe en una prisión de máxima seguridad.",
          " Joel Kinnaman, Rosamund Pike, Common", "2hr 00m", "Ingles/Español", 2019, "https://www.youtube.com/watchv=RSmuxxE2l18&ab_channel=INOPIAFILMS", "150").
peliculas(4,accion,"Greyhound","Luego de la entrada de los Estados Unidos a la Segunda Guerra Mundial, un comandante sin experiencia de la armada tendrá que liderar un convoy que está siendo perseguido por un submarino alemán",
          " Tom Hanks, Elisabeth Shue, Stephen Graham", "1hr 40m", "Ingles/Español", 2020, "https://www.youtube.com/watch?v=eyzxu26-Wqk", "180").
peliculas(5, accion,"Shadow in the Cloud","Una piloto de la Segunda Guerra Mundial que viaja con unos documentos secretos en una fortalexa B-17 se encuentra con una presencia maligna a bordo.",
          " Chloë Grace Moretz, Nick Robinson, Beulah Koale", "2hr 10m", "Ingles/Español", 2021, "https://www.youtube.com/watch?v=dYwJlyFga3s", "150").
peliculas(6,accion,"Villain","Eddie Frank solía ser un criminal, pero ahora intenta reconectar con su hija y pagar la deuda de su hermano. A pesar de sus esfuerzos, tendrá que volver a la vida de crimen. ",
          " Craig Fairbrass, George Russo, Izuka Hoyle", "1hr 47m", "Ingles/Español", 2020, "https://www.youtube.com/watch?v=VF7db98IdQw", "300").
peliculas(7,accion,"The Invisible Man","Cecilia decide escapar de su relación abusiva, lo cual conlleva a que su ex se quite la vida. Cuando se le notifica a la mujer que ha heredado la fortuna de su ex, comenzará a sospechar que su muerte era un engaño cuando una serie de coincidencias aterradoras la llevan a pensar que quizás no esté muerto.",
          "Aldis Hodge, Anthony Wong, Benedict Hardie", "2hr 15m", "Ingles/Español", 2021, "https://www.youtube.com/watch?v=WO_FJdiY9dA", "280").
peliculas(8,accion,"Lost Bullet","Un delincuente de crímenes pequeños ahora trabaja como mecánico para la policía, pero tendrá que defender su inocencia cuando su mentor es asesinado por un grupo de policías corruptos.",
          "Alban Lenoir, Nicolas Duvauchelle, Ramzy Bedia", "1hr 40m", "Ingles/Español", 2021, "https://www.youtube.com/watch?v=hSFnUc0JvbA", "250").
peliculas(9,accion,"Shadow","La historia se desarrolla en el condado de Pei, donde son gobernados por un rey despiadado. Su corte constantemente traiciona al comandante de su ejército y, para defenderse, creó una sombra, un doble de sí mismo que puede engañar incluso a su rey.",
          "Deng Chao, Sun Li, Zheng Kai", "2hr 05m", "Ingles/Español", 2019, "https://www.youtube.com/watch?v=AGetemRDuVY", "200").
peliculas(10,accion,"Dragged Across Concrete","Un policía que está cerca de retirarse decide convencer a su compañero de hacer un robo elaborado que involucra atrapar a unos ladrones y robarlos a ellos, pero no todo sale como planearon.",
          "Mel Gibson, Vince Vaughn, Tory Kittles, Michael Jai", "1hr 55m", "Ingles/Español", 2019, "https://www.youtube.com/watch?v=2p5pdWyyZoc", "254").

peliculas(11,aventura, "Vengadores: Infinity War","Un nuevo peligro acecha procedente de las sombras del cosmos. Thanos, el infame tirano intergaláctico, tiene como objetivo reunir las seis Gemas del Infinito, artefactos de poder inimaginable, y usarlas para imponer su perversa voluntad a toda la existencia. Los Vengadores y sus aliados tendrán que luchar contra el mayor villano al que se han enfrentado nunca, y evitar que se haga con el control de la galaxia.",
          "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo","2hr 40m","Ingles/Español" , 2018 ,"https://www.youtube.com/watch?v=6ZfuNTqbHE8", "250").
peliculas(12,aventura, "Jurassic Park","John Hammond, magnate propietario de la empresa multinacional en bioingeniería InGen, ha soñado toda su vida con construir el mayor parque de atracciones del mundo. Una isla en Costa Rica donde habiten las criaturas más espectaculares que han pisado la Tierra: los dinosaurios. Pese a la extinción de estos reptiles, InGen ha logrado clonar diversas especies mediante la manipulación de segmentos de ADN de la propia sangre de dinosaurio, encontrada en mosquitos fosilizados en ámbar.",
          "Sam Neill, Laura Dern, Jeff Goldblum","2hr 24m","Ingles/Español" , 2013 ,"https://www.youtube.com/watch?v=nFMqT3f3XU", "150").
peliculas(13,aventura, "Indiana Jones: En busca del arca perdida","El arqueólogo Indiana Jones necesita encontrar el Arca de la Alianza, una reliquia bíblica que contiene los Diez Mandamientos y que convierte en invencible a su poseedor. Jones deberá adelantarse a los nazis, quienes también buscan el Arca.",
          "Harrison Ford, Karen Allen,Paul Freeman","2hr 24m","Ingles/Español" , 1981 ,"https://www.youtube.com/watch?v=KGW_5fPY6As", "130").
peliculas(14,aventura, "Shrek Tercero","Cuando el Rey Harold enferma, Shrek y la Princesa Fiona descubren que tendrán que dirigir la Tierra Muy Muy Lejana a menos que puedan encontrar al Príncipe Artie, el verdadero heredero, y llevarlo a casa. Desafortunadamente, no tiene interés en ser rey; no obstante, Shrek, Burro y el Gato con Botas planean recuperarlo. Mientras tanto, la Princesa Fiona le pide ayuda a sus compañeras heroínas para alejar del trono al Príncipe Encantador.",
          "Mike Myers, Cameron Diaz, Eddie Murphy","2hr 30","Ingles/Español" , 2007 ,"https://www.youtube.com/watch?v=7j9fb9h2eyo", "250").
peliculas(15,aventura, "Jumanji","La historia de un juego mágico que libera una estampida de peligros de la selva contra sus jugadores y un hombre que desapareció en 1969 mientras jugaba.",
          "Robin Williams,  Kirsten Dunst, Bebe Neuwirth, Bradley Pierce","2hr 40m","Ingles/Español" , 1995 ,"https://www.youtube.com/watch?v=veszTagaXik", "100").
peliculas(16,aventura, "King Kong","Un grupo de exploradores, liderado por un extrovertido director de cine, visitan Skull Island para investigar todo lo relacionado con las leyendas del gorila gigante llamado King Kong. Ahí encuentran una jungla llena de criaturas prehistóricas.",
          "Peter Jackson, Naomi Watts, Jack Black","1hr 40m","Ingles/Español" , 2005 ,"https://www.youtube.com/watch?v=AYaTCPbYGdk", "180").
peliculas(17,aventura, "Okja","Una criatura gigante y la niña que la crió quedan atrapadas en medio de la lucha de poder entre defensores de animales, una corporación y la ética científica.",
          "Tilda Swinton, Jake Gyllenhaal, Steven Yeun","1hr 30m","Ingles/Español" , 2017 ,"https://www.youtube.com/watch?v=bRsySStHw7M", "200").
peliculas(18,aventura, "Robin Hood","En la Inglaterra del siglo XIII, un arquero habilidoso y sus hombres enfrentan a un déspota y evitan que se desate una guerra civil.",
          "Russell Crowe, Cate Blanchett, Mark Strong, Oscar Isaac","1hr 20m","Ingles/Español" , 2010 ,"https://www.youtube.com/watch?v=fQ6zXDSgwIY", "150").
peliculas(19,aventura, "Raya y el ultimo dragón","Raya, una guerrera solitaria, debe localizar a un dragón legendario para restaurar su tierra fracturada y a su gente dividida.",
          "Awkwafina,Kelly Marie Tran, Gemma Chan,Sandra Oh","1hr 50m","Ingles/Español" , 2021 ,"https://www.youtube.com/watch?v=hTh2-WnW1RI", "300").
peliculas(20,aventura, "Monster Hunter: la cacería comienza","En un mundo extraño, la teniente Artemis y su equipo de soldados de elite deben unir fuerzas con un misterioso cazador para luchar contra poderosos monstruos.",
          "Milla Jovovich, Tony Jaa, Ron Perlman","2hr 01m","Ingles/Español" , 2021 ,"https://www.youtube.com/watch?v=l_QbQ-QV7vk", "240").

peliculas(21,fantasia, "El laberinto del fauno","En la España de 1944, la joven Ofelia y su madre enferma llegan al lugar en el que se encuentra el nuevo esposo de su madre, un sádico oficial del Ejército que intenta aplastar el levantamiento de una guerrilla. Mientras explora un antiguo laberinto, Ofelia conoce al fauno Pan, quien le dice que ella es una legendaria princesa perdida y debe completar tres peligrosas tareas para obtener la inmortalidad.",
          "Ivana Baquero, Doug Jones, Sergi López","2hr 30m","Español" , 2006 ,"https://www.youtube.com/watch?v=FGzvvUBXj5M", "350").
peliculas(22,fantasia, "Coraline y la puerta secreta","Una niña de 11 años, se muda a un nuevo hogar junto a sus padres. Allí, descubre una puerta secreta que, cuando la atraviesa, permite a la joven vivir una vida paralela, donde sus padres son muchos más atentos con ella y sus vecinos son más amigables. Pronto, la aventura comienza a ser un poco siniestra y peligrosa y Coraline debe hacer hasta lo imposible para regresar a casa.",
          "Dakota Fanning, Teri Hatcher,Keith David","1hr 50m","Ingles/Español" , 2009 ,"https://www.youtube.com/watch?v=ttTeM08nBrs", "200").
peliculas(23,fantasia, "La forma del agua","Elisa, muda desde que era un bebé, trabaja como limpiadora nocturna en un centro de investigación aeroespacial. Una noche, mientras está limpiando en un zona de alta seguridad, ve cómo llevan al laboratorio una cápsula con un extraño ser en su interior. Se trata de un hombre anfibio, del que se enamora. A partir de entonces, Elisa elabora un plan para liberar al mutante.",
          "Sally Hawkins, Doug Jones, Michael Shannon, Octavia Spencer","2hr 00m","Ingles/Español" , 20117 ,"https://www.youtube.com/watch?v=ITqLYivTuh4", "240").
peliculas(24,fantasia, "Un monstruo viene a verme","Conor, un joven de 12 años que tiene que lidiar con el abuso de sus compañeros de clase y con la enfermedad de su madre, la cual padece un tipo cáncer en fase terminal. Una noche, el tejo del jardín de su casa se convierte en una misteriosa criatura, un monstruo que ayudará al muchacho a escapar de sus propios miedos.",
          "Liam Neeson, Felicity Jones, Lewis MacDougall","1hr 50m","Ingles/Español" , 2016 ,"https://www.youtube.com/watch?v=1-fubC9JN50", "180").
peliculas(25,fantasia, "Charlie y la fábrica de chocolate ","Charlie Bucket quien, tras ganar un concurso, tiene la oportunidad de visitar la fábrica de chocolates de la conocida marca Wonka. Allí está Willy, el estrambótico jefe de la fábrica y sus trabajadores, los Oompa Loompa.",
          "Johnny Depp, Freddie Highmore, AnnaSophia Robb, Julia Winter","2hr 30m","Ingles/Español" , 2005 ,"https://www.youtube.com/watch?v=BGem82vCZNM", "180").
peliculas(26,fantasia, "Las crónicas de Narnia: El león, la bruja y el ropero.","La historia arranca con las vivencias de cuatro niños que, en medio del caos de la Guerra, encuentran en un ropero la entrada a un mundo fantástico llamado Narnia, el cual está dominado por Bruja Blanca. Pronto, los niños se alían con el león Aslan para salvar Narnia y traer la paz en el reino.",
          "Georgie Henley, William Moseley, Anna Popplewell, Skandar Keynes","2hr 40m","Ingles/Español" , 2005 ,"https://www.youtube.com/watch?v=PKEimNXpuQo", "280").
peliculas(27,fantasia, "Animales fantásticos y dónde encontrarlos","El mago experto en zoología Newt Scamander hace una breve parada en Nueva York mientras viaja catalogando y capturando criaturas mágicas por el mundo. Jacob, un humano corriente, provoca por error que las criaturas escapen y se oculten por la ciudad. Scamander tendrá que atraparlas de nuevo, antes de que causen problemas.",
          "Eddie Redmayne, Katherine Waterston, Ezra Miller","1hr 50m","Ingles/Español" , 2016 ,"https://www.youtube.com/watch?v=W45vhTxKeQE", "230").
peliculas(28,fantasia, "Miss Peregrine y los niños peculiares","Mientras investiga un misterio que le legó su abuelo, un adolescente encuentra en la costa de Gales una isla en la que habitan niños con poderes especiales y terribles enemigos que los amenazan. ",
          "Eva Green, Asa Butterfield, Ella Purnell, Samuel L. Jackson","1hr 50m","Ingles/Español" , 2016 ,"https://www.youtube.com/watch?v=7tI7x-lEpTE", "201").
peliculas(29,fantasia, "Alicia en el país de las maravillas","A sus 19 años, Alicia está a punto de recibir la propuesta de matrimonio de Hamish Ascot. La muchacha, nada preparada para el suceso, decide perseguir al Conejo Blanco y llega al País de las Maravillas, un lugar que ya había visitado hace una década.",
          "Mia Wasikowska, Johnny Depp,  Helena Bonham Carter, Anne Hathaway","2hr 10m","Ingles/Español" , 2010 ,"https://www.youtube.com/watch?v=LEejGf69tT8", "250").
peliculas(30,fantasia, "Gretel y Hansel: un oscuro cuento de hadas","Dos jóvenes de 13 y 9 años viven inmersos en la pobreza desde el fallecimiento de su padre. Su madre está casada con un hombre cruel que aterroriza a los niños. Gretel y Hansen emprenden una aventura con la esperanza de encontrar un futuro mejor, sin embargo, en el bosque se cruzan con todo tipo de personas hasta llegar a la casa de Holda, mujer de la que les será difícil escapar.",
          "Sophia Lillis, Jessica De Gouw, Samuel Leakey","1hr 45m","Ingles/Español" , 20 ,"https://www.youtube.com/watch?v=fNqxgghCdXI", "230").

peliculas(31,comedia, "El hombre mosca","El hombre mosca (Safety Last!) es una película protagonizada por Harold Lloyd, uno de los cómicos más legendarios del séptimo arte. En ella, el actor se pone en la piel de un hombre que emigra a la ciudad en busca de una vida mejor. Allí empieza a trabajar como empleado de unos grandes almacenes.",
          "Harold Lloyd, Mildred Davis, Bill Strother, Noah Young, Westcott Clarke","1hr 13m","Ingles" , 1923 ,"https://www.youtube.com/watch?v=wdsSz2iO-Zo", "85").
peliculas(32,comedia, "El maquinista de la General","El maquinista de la general (The General) es otra joya del cine de Keaton. Está ambientada en la Guerra de Secesión en 1861. En ella interpreta a Johnny Gray, un maquinista de tren, que es rechazado en las listas del ejército y se ve envuelto en una serie de situaciones absurdas con su locomotora. El viaje en tren se convierte en el verdadero protagonista de la película, un trayecto lleno de humor, suspense y gags que hacen de esta cinta una comedia intemporal.",
          "Buster Keaton, Marion Mack,  Glen Cavende, Jim Farley","1hr 15m","Ingles" , 1926 ,"https://www.youtube.com/watch?v=Jw7ZJDllPWU", "100").
peliculas(33,comedia, "Arizona Baby","Educado en Arizona o Arizona Baby es una original comedia de los hermanos Coen que narra la historia de un ladrón de supermercados (Nicolas Cage) que se enamora de una funcionaria de prisiones (Holly Hunter) y se casa con ella. Durante su matrimonio descubren que no pueden ser padres y deciden robar un bebé a unos padres que acaban de tener quintillizos. Esta película destaca por los personajes que, envueltos en situaciones inverosímiles, regalan diálogos inmejorables cargados de un buen sentido del humor.",
          "Nicolas Cage, Holly Hunter, John Goodma, William Forsythe","1hr 34m","Ingles" , 1987 ,"https://www.youtube.com/watch?v=OjWu8i6eMZo", "150").
peliculas(34,comedia, "Solo en casa","Macaulay Culkin, un niño de 8 años que se queda solo en su casa por un descuido de su familia. Mientras tanto, un par de ladrones pretenden asaltar las casas de todo el vecindario, lo que no saben es que el joven les hará la vida imposible cuando entren en su casa.",
          "Macaulay Culkin, Catherine O’Hara, Joe Pesci, Daniel Stern","1hr 03m","Ingles" , 1990 ,"https://www.youtube.com/watch?v=GKBxj8mKQ6s", "110").
peliculas(35,comedia, "Como Dios","Un reportero cansado de lo que ocurre a su alrededor y lo reprocha constantemente. Así que Dios le reta a cambiar los roles y le otorga sus poderes. Es entonces cuando descubrirá que ser Dios no es nada fácil y aprovechará su poder para poner aún más patas arriba su vida.",
          "Morgar Freeman, Jim Carrey, Steve Carey, Catherine Bell","1hr 01m","Ingles" , 2003 ,"https://www.youtube.com/watch?v=icuTE1A2e2E", "200").
peliculas(36,comedia, "Atrapado en el tiempo","n meteorólogo televisivo que viaja a un pequeño pueblo para cubrir el Día de la marmota. Una tormenta interrumpe su regreso y tiene que hospedarse en el lugar durante una noche. Al día siguiente, Phil descubre que está atrapado en el Día de la marmota, a partir de ese momento, lo revive en bucle una y otra vez.",
          "Bill Murray, Andie MacDowell, Harold Ramis","1hr 01m","Ingles/Español" , 1993 ,"https://www.youtube.com/watch?v=sqQHQ9PNV0Y", "150").
peliculas(37,comedia, "Tootsie","Un actor frustrado que no está pasando por su mejor momento. Un día decide presentarse a un casting disfrazado de mujer y consigue un papel para un personaje femenino en una serie televisiva.",
          "Dustin Hoffman, Jessica Lange, Sydney Pollack","1hr 19m","Ingles/Español" , 20 ,"https://www.youtube.com/watch?v=4U9hfQujTcM", "130").
peliculas(38,comedia, "La boda de mi mejor amiga","rotagonismo femenino, repartos rebosantes de cómicos de mucho talentoo que propicia tronchantes improvisaciones. Aunque aún no ha gestado una comedia absolutamente redonda",
          "Melissa McCarthy, Kristen Wiig, Maya Rudolph, Rose Byrne","1hr 32m","Ingles" , 20011 ,"https://www.youtube.com/watch?v=NQuoFfRpdSo", "180").
peliculas(39,comedia, "Un tipo serio","La historia de un profesor de matemáticas de los años sesenta (gigantesco Michael Stuhlbarg) que atraviesa una crisis existencial y se encomienda a tres rabinos para hallar respuestas es de las que provocan tanto cachondeo como desconcierto.",
          "Michael Stuhlbarg, Richard Kind, Sari Lenick, Fred Melamed","1hr 46m","Ingles/Español" , 2009 ,"https://www.youtube.com/watch?v=rbW8ZlVkiuA", "250").
peliculas(40,comedia, "Supersalidos","ea con un carnet falso con nombre gracioso (como McLovin), o colándose en una fiesta y bailando con la novia del anfitrión para robarle la bebida, el objetivo de la película es conseguir algo de beber a cualquier precio para gustarle a una chica del instituto y no llegar virgen a la universidad.",
          "Jonah Hill,Seth Rogen, Michael Cera, Christopher Mintz-Plasse","1hr 19m","Ingles/Español" , 2007 ,"https://www.youtube.com/watch?v=b8ht6ObDlyQ", "170").

peliculas(41,guerra,"Johnny tomo su fusil","Escrita y dirigida por Dalton Trumbo, quien adaptó su propia novela para la gran pantalla, podríamos catalogar a 'Johnny cogió su fusil' como la gran cinta antibelicista de la historia y como uno de los ejercicios más descorazonadores, deprimentes y duros que encontraremos en esta lista; que continúa removiendo conciencias con la misma perfección que hace casi cinco décadas. Puede que no sea ejemplar en términos de puesta en escena y forma, pero los debates morales que plantea y el modo en que captura el calvario de una víctima de la guerra son dignos de todo elogio.",
          "Timothy Bottoms, Jason Robards,  Donald Sutherland,","1hr 51m","Ingles", 1971, "https://www.youtube.com/watch?v=qB7j4C6hBBA", "250").
peliculas(42,guerra,"Dunkerque","Como a cualquier largometraje de Christopher Nolan, a 'Dunkerque' no le faltan detractores, pero es complicado refutar la idea de que este largometraje es una de las mayores virguerías que nos ha dado el género en lo que llevamos de siglo XXI —si no la mayor—.  Con una narrativa que juega con el concepto del tiempo muy en la línea del británico, con una ejecución magistral —soberbia experiencia disfrutarla proyectada en 70mm— y, sobre todo, con un empleo del sonido que alimenta el incesante crescendo de poco más de hora y media que ofrece, 'Dunkerque' es, hasta la fecha, el magnum opus de su autor.",
          "Fionn Whitehead, Mark Rylance, Kenneth Branagh","1hr 47m","Ingles/Español", 2017, "https://www.youtube.com/watch?v=F-eMt3SrfFU&feature=youtu.be", "150").
peliculas(43,guerra,"En tierra hostil","009 fue el año en que, sin que nadie lo esperase, Kathryn Bigelow, con un largometraje de unos irrisorios 15 millones de dólares de presupuesto, barrió del mapa a gigantescas superproducciones y a grandes autores consagrados en los Óscar.",
          "eremy Renner, Anthony Mackie, Brian Geraghty","1hr 41m","Ingles/Español", 2009, "https://www.youtube.com/watch?v=AIbFvqFYRT4&feature=youtu.be", "300").
peliculas(44,guerra,"La caída del Halcón Negro","Puede que, a nivel discursivo, 'Black Hawk derribado' no sea una cinta particularmente elogiable. Pero a quién le importa esto cuando Ridley Scott, en un alarde de virtuosismo técnico y narrativo, llevó el hiperrealismo de Spielberg en 'Salvar al soldado Ryan' a nuevas cotas con un ejercicio asfixiante, inmersivo y sumamente enérgico que te sumerge en la crudeza de un conflicto armado, haciéndote formar parte de él con un lenguaje que no teme en coquetear conel documental. Cruda, violenta y sin un ápice de moral —para bien o para mal—. ",
          "Josh Hartnett, Eric Bana, Ewan McGregor, Tom Sizemore","2hr 32m","Ingles/Español", 2001, "https://www.youtube.com/watch?v=2GfBkC3qs78&feature=youtu.behttps://www.youtube.com/watch?v=2GfBkC3qs78&feature=youtu.be", "250").
peliculas(45,guerra,"Lebanon","Ganadora del León de Oro en el Festival de Venecia, esta película israelí cuenta los horrores de la Guerra del Líbano de 1982 desde el interior de un tanque. Veinticuatro horas en las que un grupo de soldados (y también nosotros) sienten la claustrofobia no solo del reducido espacio en el que se encuentran, sino también de todo el conflicto. Un filme de Samuel Maoz lleno de reflexiones y sobre todo emociones.",
          "Oshri Cohen, Yoav Donat, Reymond Amsalem, Ashraf Barhom","1hr 34m","Ingles/Español", 2009, "https://www.youtube.com/watch?v=IMRD3z_mTqI", "180").
peliculas(46,guerra,"Salvar al soldado Ryan","Esa primera escena en el desembarco de Normandía no se nos borrará nunca de la cabeza. Y, aun así, ese sólo es el principio de una historia profundamente violenta y emocionante, con esa capacidad innegable de Spielberg para unirnos de por vida -o, al menos, durante tres horas- a unos icónicos personajes. ",
          "Tom Hanks, Vin Diesel, Matt Damon, Adward ","2hr 30m","Ingles/Español", 1998, "https://www.youtube.com/watch?v=pWhQvZJiU0Q", "90").
peliculas(47,guerra,"Rescate al amanecer","Durante la Guerra de Vietnam, Dieter Dengler (Christian Bale), un piloto de combate estadounidense, es derribado sobre Laos y es capturado por los soldados enemigos. Internado en un campamento para prisioneros de guerra. Dengler y sus compañeros prisioneros (Steve Zahn, Jeremy Davies) enfrentan torturas, hambre y enfermedades mientras esperan la oportunidad de escapar.",
          "Christian Bale, Steve Zahn, Jeremy Davis","2hr 06m","Ingles/Español", 2006, "https://www.youtube.com/watch?v=UNm9Tzo5rvI", "150").
peliculas(48,guerra,"La delgada línea roja","Durante la Primera Guerra Mundial, dos jóvenes soldados británicos reciben una orden, aparentemente, imposible de ejecutar: en una carrera contra el reloj, deben infiltrarse en territorio enemigo para entregar un mensaje que podría salvar a miles de compañeros.",
          "Jim Caviezel, Sean Penn, Nick Nolte,","1hr 59m","Ingles/Español", 2019, "https://www.youtube.com/watch?v=M6euo4jMaUw", "300").
peliculas(49,guerra,"Hasta el último hombre","Desmond Doss (Andrew Garfield), un joven contrario a la violencia, se alista en el ejército de los EEUU con el objetivo de servir como médico durante la guerra. Tras enfrentarse a las autoridades militares y a un juicio por su negativa a empuñar un arma, consigue su objetivo y es enviado a servir como médico al frente japonés. A pesar de ser recibido con recelo por todo el batallón durante la salvaje toma de Okinawa, Desmond decide jugarse la vida en la peor de las condiciones, demostrando su valor salvando a 75 hombres heridos consiguiendo el respeto de los soldados.",
          "George MacKay, Dean-Cha Chapman, Richard Madden, Benedict Cumberba","2hr 19m","Ingles/Español", 2016, "https://www.youtube.com/watch?v=HpW6qzO4LHI", "350").
peliculas(50,guerra,"1917","Durante la Primera Guerra Mundial, dos jóvenes soldados británicos reciben una orden, aparentemente, imposible de ejecutar: en una carrera contra el reloj, deben infiltrarse en territorio enemigo para entregar un mensaje que podría salvar a miles de compañeros.",
          "Andrew Garfield, Luke Bracey, Teresa Palmer","1hr 58m","Ingles/Español", 2016, "https://www.youtube.com/watch?v=M6euo4jMaUw", "250").

peliculas(51,romance,"Titanic","Durante el viaje inaugural del impresionante transatlántico Titanic, Jack y Rose se conocen. Él es un joven pobre que sueña con una nueva vida en Estados Unidos, mientras que ella es una joven de buena familia obligada a casarse con un millonario engreído.",
          "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Gloria Stuart, Bill Paxton","3hr 14m", "Ingles", 1997, "https://www.youtube.com/watch?v=kVrqfYjkTdQ", "250").
peliculas(52,romance,"10 razones para odiarte","La chica más popular del instituto, Bianca Stratford, se encuentra ante un problema: según una regla impuesta por su padre, no puede ir a fiestas ni salir con chicos hasta que Cat, su hermana mayor, haga lo mismo.",
          "Heath Ledger, Julia Stiles, Joseph Gordon Levit","1 h 37 m", "Ingles", 1999, "https://www.youtube.com/watch?v=7JakjyFsFjE", 150).
peliculas(53,romance,"Forrest Gump","s un hombre simple con bajo coeficiente intelectual que a pesar de su discapacidad tiene una vida extraordinaria que lo lleva a presenciar los eventos históricos más significativos de la segunda mitad del siglo XX. Excediendo las expectativas de los demás supera los desafíos que le plantea su condición a fuerza de perseverancia coraje y amor.",
          "Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson","2hr 36m", "Ingles", 1994, "https://www.youtube.com/watch?v=Cyh1LpxnaxI", "250").
peliculas(54,romance,"500 días con ella","Tom creció bajo el influjo del triste pop británico, con la idea de que no sería feliz hasta encontrar el amor de su vida. Summer, sin embargo, marcada por el divorcio de sus padres, creció sin creer en el amor. Se gustan y a ambos les gusta la música de The Smiths. Quizá eso sea suficiente.",
          "Joseph Gordon-Levitt, Zooey Deschanel","1hr 35m", "Ingles/Español", 2009, "https://www.youtube.com/watch?v=b-wEibP-xLE", "150").
peliculas(55,romance,"Call Me by Your Name","Elio es un muchacho que pasa las vacaciones con sus padres en una villa italiana. Al poco se les une Oliver, un graduado que va a estudiar con el padre de Elio y que traba buena amistad con el joven. Su relación pronto se convierte en algo más.",
          "Armie Hammer, Timothée Chalamet, Michael Stuhlbarg","2hr 12m", "Ingles", 2017, "ttps://www.youtube.com/watch?v=Z9AYPxH5NTM", "200").
peliculas(56,romance,"La La Land","Mia es una aspirante a actriz y Sebastián es un cantante de Jazz. Ellos luchan a diario por destacarse en una ciudad tristemente conocida por destrozar esperanzas y quebrar corazones. Las ilusiones de los dos van de la mano con la música y nunca bajarán los brazos para encontrar la tan ansiada felicidad, a pesar de las dificultades que se les presentan en este duro camino de perseguir los sueños.",
          "Ryan Gosling, Emma Stone, Terry Walters","2hr 08m", "Ingles", 2016, "https://www.youtube.com/watch?v=45s24h98iOc", "300").
peliculas(57,romance,"Diario de una pasión","En una residencia de ancianos, un hombre lee a una mujer una historia de amor escrita en su viejo cuaderno de notas. Es la historia de Noah Calhoun y Allie Hamilton , dos jóvenes adolescentes de Carolina del Norte que, a pesar de vivir en dos ambientes sociales muy diferentes, se enamoraron profundamente y pasaron juntos un verano inolvidable, antes de ser separados, primero por sus padres, y más tarde por la guerra.",
          "Ryan Gosling, Rachel McAdams, James Garner","2hr 03m", "Ingles", 2004, "https://www.youtube.com/watch?v=YYz8i3hmqWA", "150").
peliculas(58,romance,"La forma del agua","Durante la Guerra Fría Elisa, una joven muda, trabaja en un laboratorio gubernamental de alta seguridad. Pero su vida cambia cuando descubre un experimento secreto: un hombre anfibio que se encuentra recluido en un tanque. Pronto se desarrolla una cercanía alimentada por la soledad que rodea a los dos personajes, dando como resultado consecuencias inesperadas.",
          "Sally Hawkins, Michael Shannon, Richard Jenkins","2hr 02m", "Ingles", 2018, "https://www.youtube.com/watch?v=gfVe2puMBs0", "280").
peliculas(59,romance,"Yo antes de ti","William Traynor fue un hombre rico y exitoso, empresario de renombre que vivía su vida al máximo. Hombre lleno de aspiraciones y metas por cumplir. No obstante, Will no se esperaba que un día todo cambiaría para él. Era un día lluvioso, y una moto en exceso de velocidad chocó contra él, llevándose la capacidad de mover su cuerpo y al mismo tiempo los sueños que tanto anhelaba cumplir.",
          "Jenna Coleman, Charles Dance, Janet McTeer","1hr 46m", "Ingles", 2016, "https://www.youtube.com/watch?v=PQ0RIeH__hI", "50").
peliculas(60,romance,"Bajo la misma estrella","Hazel tiene dieciséis años, está enferma de cáncer desde pequeña y sobrevive gracias a un pequeño milagro médico y a la bombona de oxígeno que la acompaña todo el tiempo. Un día, en un grupo de apoyo para chicos con cáncer, Hazel conoce a Gus, que ya ha superado la enfermedad. Ambos comparten un ácido sentido del humor, un desprecio por lo convencional y un amor que los arrastra hacia un viaje inolvidable.",
          "Shailene Woodley,  Ansel Elgort, Laura Dern","2hr 06m", "Ingles", 2014, "https://www.youtube.com/watch?v=9Lt8QAZkc94", "250").

peliculas(61,infantil,"Toy Story","Los juguetes de Andy, un niño de 6 años, temen que haya llegado su hora y que un nuevo regalo de cumpleaños les sustituya en el corazón de su dueño. Woody, un vaquero que ha sido hasta ahora el juguete favorito de Andy, trata de tranquilizarlos hasta que aparece Buzz Lightyear, un héroe espacial dotado de todo tipo de avances tecnológicos.",
          "Tom Hanks, Tim Allen, Don Rickles, Jim Varney","1hr 21m", "Ingles", 1995, "https://www.youtube.com/watch?v=rNk1Wi8SvNc", "150").
peliculas(62,infantil,"Bichos, una aventura en miniatura","Flik es una hormiga que comienza un viaje para buscar ayuda luego de que varios saltamontes amenazan su colonia para que consiga alimentos. En medio del camino, Flik conocerá a un grupo de bichos de circo y empezará una mágica aventura.",
          "Dave Foley, Kevin Spacey, Julia Louis-Dreyfus","1hr 35m", "Ingles", 1998, "https://www.youtube.com/watch?v=38wy8FR_8aM", "250").
peliculas(63,infantil,"Monster Inc","En la ciudad de Monstruópolis, el corpulento de pelos azules James P. Sulley Sullivan y su mejor amigo, un divertido monstruo de solo un ojo llamado Mike Wazowski, trabajan en la Monsters Inc, una fábrica de procesamiento de gritos que prospera a costa de los gritos de niños aterrados por monstruos que viven bajo sus camas y dentro de sus roperos. El trabajo de Sulley, Mike y sus colegas es mantener la fábrica en pie. Pero, cuando Sulley y Mike son seguidos por una valiente niñita llamada Boo hasta el mundo de los monstruos, cabrá a ellos enviarla de vuelta antes que alguien la descubra. Con el agravante que los monstruos se mueren de miedo de los chicos",
          "John Goodman, Billy Crystal, Mary Gibbs","1hr 32m", "Ingles/Español", 2001, "https://www.youtube.com/watch?v=uzkkh-1A_kY", "100").
peliculas(64,infantil,"Cars","Rayo Mcqueen es un joven y prometedor coche de carreras que vive la vida por el carril rápido hasta que coge un desvío en su camino hacia la carrera más importante de su vida. Retenido en Radiator Springs, una ciudad olvidada en la vieja ruta 66, conoce a Sally, Mate, Doc Hudson y una gran variedad de extravagantes personajes.",
          "Owen Wilson, Paul Newman, Bonnie Hunt","1hr 57m", "Ingles", 2006, "https://www.youtube.com/watch?v=SbXIj2T-_uk", "300").
peliculas(65,infantil,"Los increíbles","Bob Parr y su mujer Helen eran los más grandes combatientes del crimen, salvando vidas y luchando contra villanos a diario. Quince años después, esta singular pareja ha sido forzada a adoptar una identidad civil y a retirarse a las afueras donde viven vidas normales con sus tres hijos: Violeta, Dash y Jack-Jack. Ansioso por volver a la acción, Bob encuentra su oportunidad cuando una misteriosa llamada le lleva a una remota isla para realizar una misión de alto secreto. Pronto descubrirá el súper esfuerzo familiar que supone salvar al mundo de la destrucción total.",
          "Craig T. Nelson, Holly Hunter, Spencer Fox","1hr 55m", "Ingles", 2004, "https://www.youtube.com/watch?v=jWcUTQyTUfc", "80").
peliculas(66,infantil,"Ratatouille","El destino lleva a Remy a las alcantarillas de París, pero su situación no podría ser mejor ya que se encuentra justo debajo de un restaurante que se ha hecho famoso gracias a Auguste Gusteau, una estrella de la cuisine.",
          "Patton Oswalt, Brian Dennehy, Brad Garrett","1hr 51m", "Ingles", 2007, "https://www.youtube.com/watch?v=ci4bJWh8K4o", "150").
peliculas(67,infantil,"Walle","Qué ocurriría si la humanidad debiera abandonar la Tierra y alguien se olvidara de apagar el último robot? Tras setecientos solitarios años haciendo aquello para lo que fue construido, esto es, limpiar el planeta, WALL-E descubre una nueva misión en su vida (además de recolectar cosas inservibles) cuando se encuentra con un lustroso robot explorador llamado EVA.",
          "Ben Burtt, Elissa Knight, Jeff Garlin,","1hr 38m", "Ingles", 2008, "https://www.youtube.com/watch?v=IYPe2oWBV_w", "200").
peliculas(68,infantil,"Buscando a Nemo","La vida en la Gran Barrera de Coral está repleta de peligros para un diminuto pez payaso. Por eso, a Marlin, un padre viudo decidido a proteger a Nemo, su único hijo, el miedo y la ansiedad no lo abandonan ni un solo instante.",
          "Albert Brooks, Ellen DeGeneres, Alexander Gould","1hr 40m", "Ingles/Español", 2003, "https://www.youtube.com/watch?v=XD7kh7BCnNY", "170").
peliculas(69,infantil,"Cenicienta","Cenicienta era una hermosa y bondadosa joven, que vivía en un palacio junto su cruel madrastra y sus dos hermanastras. Ellas la obligaban a ocuparse de las labores más duras del hogar, como si fuera la última de las criadas. Sucedió que el hijo del Rey celebró un gran baile. Cenicienta ayudó a sus egoístas hermanastras a vestirse y peinarse para la fiesta. Cuando se hubieron marchado, la pobre niña se echó a llorar amargamente porque también le hubiera gustado ir al baile.",
          "Ilene Woods, Eleanor Audley, Luis Van Rooten","1hr 14m", "Ingles", 1950, "https://www.youtube.com/watch?v=Pl8n2m0WyAI", "250").
peliculas(70,infantil,"Los pitufos","Gargamel descubre la aldea mágica de los pitufos y provoca con sus malas artes que la abandonen y se dispersen por el bosque. Por desgracia, uno de ellos se equivoca de camino y, junto con otros pitufos, entra en una ruta prohibida. La luna azul y un portal mágico los transporta a Manhattan, Nueva York.",
          "Neil Patrick, Harris Jayma Mays, Sofía Vergara, Tim Gunn","1hr 43m", "Ingles/Español", 2011, "https://www.youtube.com/watch?v=3-unThbvijE", "200").

peliculas(71,ciencia_ficcion,"Ex-Máquina","Un joven programador que trabaja en una compañía de Internet es elegido para evaluar las capacidades y la conciencia de una hermosa y sofisticada robot.",
          "Alicia Vikander, Oscar Isaac, Domhnall Gleeson", "1h 48m", "Ingles", 2014,"https://www.youtube.com/watch?v=qSwobe3uIII","300").
peliculas(72,ciencia_ficcion,"Interstellar","Gracias a un descubrimiento, un grupo de científicos y exploradores, encabezados por Cooper, se embarcan en un viaje espacial para encontrar un lugar con las condiciones necesarias para reemplazar a la Tierra y comenzar una nueva vida allí.",
          "Matthew McConau, Anne Hathaway, Jessica Chastain", "2h 49m", "Ingles", 20,"https://www.youtube.com/watch?v=NVw3DnN9WoA","250").
peliculas(73,ciencia_ficcion,"¿Qué le pasó a Lunes?","En un futuro en el que está prohibido tener más de un hijo, seis hermanas que fingen ser la misma para pasar inadvertidas tratan de escapar del control opresivo del Gobierno mientras buscan a la séptima hermana, que ha desaparecido.",
          "Noomi Rapace, Glenn Close, Marwan Kenzari", "2h 04m", "Ingles", 2017 ,"https://www.youtube.com/watch?v=sRIYLZJqbEY","150").
peliculas(74,ciencia_ficcion,"Area 51","Tres jóvenes teóricos de la conspiración intentan descubrir los misterios del Área 51, el enigmático lugar donde el Gobierno de los Estados Unidos supuestamente ha mantenido encuentros con seres extraterrestres.",
          "Ben Rovner, Sandra Staggs, Wray Featherstone", "1h 35m", "Ingles", 2015,"https://www.youtube.com/watch?v=jg1Jt2Ft6xg","300").
peliculas(75,ciencia_ficcion,"Life: vida inteligente","Seis astronautas descubren indicios de la existencia de vida inteligente en Marte. Cuando comienzan a investigar, se dan cuenta de que esa forma de vida está mucho más evolucionada y es infinitamente más aterradora de lo que habían supuesto.",
          "Jake Gyllenhaal, Ryan Reynolds, Rebecca Ferguson", "1h 50m", "Ingles", 20,"https://www.youtube.com/watch?v=wYhFt214F98","180").
peliculas(76,ciencia_ficcion,"Pasajeros","Dos pasajeros que viajan en hibernación a un planeta lejano despiertan, por un error técnico, 90 años antes de llegar a destino. Solos y rodeados de lujos, entre ellos surge el amor; sin embargo, descubren que hay una avería en la nave y tendrán que repararla a tiempo para salvar a las 5 000 personas que permanecen hibernando, y a sí mismos.",
          "Jennifer Lawrence, Chris Pratt", "1h 56 m", "Ingles", 2016,"https://www.youtube.com/watch?v=8JuGv5xI52w","75").
peliculas(77,ciencia_ficcion,"Un lugar en silencio","En el año 2020, unas criaturas misteriosas con un sentido auditivo extraordinario han diezmado a la población mundial. Una familia se oculta en una cabaña y se comunica mediante la lengua de signos para no ser cazados por estos monstruos.",
          "John Krasinski, Emily Blunt, Millicent Simmonds", "3h 36m", "Ingles", 2018,"https://www.youtube.com/watch?v=MxSIK-jngVA","180").
peliculas(78,ciencia_ficcion,"2067"," ambientado en un futuro distópico donde el cambio climático ha erradicado toda la vida vegetal del planeta. ... '2067' resulta un viaje interesante y atractivo, pero su gusto por acentuar el drama personal del héroe termina por jugar en contra.",
          "Kodi Smit-McPhee, Ryan Kwanten, Deborah Mailman", "1h 54 m", "Ingles", 2020,"https://www.youtube.com/watch?v=kc0YwLFHgQ8","260").
peliculas(79,ciencia_ficcion,"Pasajero inesperado","Un grupo científico está en una misión rumbo al planeta Marte. La situación se complica cuando descubren a un polizón inconsciente en el interior del transporte. El escenario se torna catastrófico cuando el sistema de soporte vital presenta fallas graves",
          "Anna Kendrick, Toni Collette, Daniel Dae Kim", "1h 56 m", "Ingles", 2021,"https://www.youtube.com/watch?v=Yf7l0qAgumg","250").
peliculas(80,ciencia_ficcion,"LUCY","Lucy, una joven que ejerce de mula para unos narcotraficantes, adquiere poderes sobrenaturales tras romperse una de las bolsas de droga que transporta y absorber los estupefacientes.",
          "Scarlett Johansson, Luc Besson Morgan Freeman", "1h 30 m", "Ingles", 2014,"https://www.youtube.com/watch?v=s0kMPeR8sVo","310").


verCatalogo(C) :-
    				peliculas(Id, X, Ti, Sin, Ac, Dur, Idio, Anio, Enl, Cos), 
    				write(Id), write("-"), write(X), 
    				write("-"), write(Ti), write("-"), 
    				write(Sin), write("-"), write(Ac), write("-"),
    				write(Dur), write("-"), write(Idio),write("-"), write(Anio), 
    				write("-"), write(Enl), write("-"), write(Cos), write(C), nl, fail.

consultarGenero(X) :-
    				peliculas(Id, X, Ti, Sin, Ac, Dur, Idio, Anio, Enl, Cos), 
    				write(Id), write("-"), write(X), 
    				write("-"), write(Ti), write("-"), 
    				write(Sin), write("-"), write(Ac), write("-"),
    				write(Dur), write("-"), write(Idio),write("-"), write(Anio), 
    				write("-"), write(Enl), write("-"), write(Cos), write("*"), nl, fail.

consultarTitulo(X) :-
    				peliculas(X, Gen, Ti, Sin, Ac, Dur, Idio, Anio, Enl, Cos), 
    				write(X), write("-"), write(Gen), 
    				write("-"), write(Ti), write("-"), 
    				write(Sin), write("-"), write(Ac), write("-"),
    				write(Dur), write("-"), write(Idio),write("-"), write(Anio), 
    				write("-"), write(Enl), write("-"), write(Cos), write("*"), nl, !.

recomendaciones(X, Y) :-
    				peliculas(Id, X, Ti, Sin, Ac, Dur, Idio, Anio, Enl, Cos), not(Id == Y),
    				write(Id), write("-"), write(X), 
    				write("-"), write(Ti), write("-"), 
    				write(Sin), write("-"), write(Ac), write("-"),
    				write(Dur), write("-"), write(Idio),write("-"), write(Anio), 
    				write("-"), write(Enl), write("-"), write(Cos), write("*"), nl, fail.

